POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video sobre node",
    "description": "Esse é o video fera",
    "duration": 180
}

###
GET  http://localhost:3333/videos

###
PUT http://localhost:3333/videos/a08e7a9f-ab98-4381-9dff-e0faab7b68db
Content-Type: application/json

{
    "title": "Video com o title diferente",
    "description": "Esse é o video fera 02",
    "duration": 3232
}

###
DELETE http://localhost:3333/videos/a08e7a9f-ab98-4381-9dff-e0faab7b68db