POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o video fera",
    "duration": 180
}

###
GET  http://localhost:3333/videos?search=node

###
PUT http://localhost:3333/videos/cf11989c-41b5-49e4-9090-78c6e675a392
Content-Type: application/json

{
    "title": "Video com o title diferente",
    "description": "Esse é o video fera 02",
    "duration": 3232
}

###
DELETE http://localhost:3333/videos/a7ac8725-09ca-4162-ace8-21f2d169b66f