POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Esse é o video fera",
    "duration": 180
}

###
GET  http://localhost:3333/videos

###
PUT http://localhost:3333/videos/cf11989c-41b5-49e4-9090-78c6e675a392
Content-Type: application/json

{
    "title": "Video com o title diferente",
    "description": "Esse é o video fera 02",
    "duration": 3232
}

###
DELETE http://localhost:3333/videos/9249e066-f5e2-4a7f-9a59-ff47e6a8589d